/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MonitoringSupervisorRole;

import Business.WorkQueue.WaterPipeLeakWorkRequest;
import Business.WorkQueue.WaterPressureWorkRequest;
import Business.WorkQueue.WaterQualityWorkRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vishakha
 */
public class CaseDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private WorkRequest request;
    private WorkQueue.RequestType type;
    public CaseDetailsJPanel(JPanel userProcessContainer,WorkRequest request,WorkQueue.RequestType type) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        this.type=type;
        populateStatusComboBox();
        caseCategoryComboBox.removeAllItems();
        populateData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    public void populateStatusComboBox()
    {
        StatusComboBox.removeAllItems();
        StatusComboBox.addItem(request.getStatus());
        StatusComboBox.setSelectedItem(request.getStatus());
    }
    public void populateData()
    {
        lblCaseID.setText(String.valueOf(request.getCaseID()));
        lblAssignedTo.setText(request.getAssignedTo()==null ? null:request.getAssignedTo().getEmployee().getName());
        lblCaseLocation.setText(request.getLocation());
        //System.out.println(request.getStatus());
        
        
        if(type.getValue().equals("WaterQualityWorkRequest"))
        {    
        txtDescription.setText(((WaterQualityWorkRequest)request).getDescription());
        txtComment.setText(((WaterQualityWorkRequest)request).getComment());
        caseCategoryComboBox.addItem(((WaterQualityWorkRequest)request).getCategory());
        caseCategoryComboBox.setSelectedItem(((WaterQualityWorkRequest)request).getCategory());
        }
        if(type.getValue().equals("WaterPressureWorkRequest"))
        {    
        txtDescription.setText(((WaterPressureWorkRequest)request).getDescription()); 
        txtComment.setText(((WaterPressureWorkRequest)request).getComment());
        caseCategoryComboBox.addItem(((WaterPressureWorkRequest)request).getCategory());
        caseCategoryComboBox.setSelectedItem(((WaterPressureWorkRequest)request).getCategory());
        }       
        if(type.getValue().equals("WaterPipeLeakWorkRequest"))
        {    
        txtDescription.setText(((WaterPipeLeakWorkRequest)request).getDescription());
        txtComment.setText(((WaterPipeLeakWorkRequest)request).getComment());
        caseCategoryComboBox.addItem(((WaterPipeLeakWorkRequest)request).getCategory());
        caseCategoryComboBox.setSelectedItem(((WaterPipeLeakWorkRequest)request).getCategory());
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caseCategoryComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        lblCaseID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        lblAssignedTo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblCaseLocation = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtComment = new javax.swing.JTextField();

        caseCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Description:");

        txtDescription.setEditable(false);
        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setEnabled(false);
        jScrollPane1.setViewportView(txtDescription);

        jLabel5.setText("Status:");

        lblCaseID.setText("<caseID>");

        jLabel1.setText("CaseID:");

        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("AssignedTo:");

        lblAssignedTo.setText("<assignedTo>");

        jLabel3.setText("Case Category:");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel6.setText("Case Location:");

        lblCaseLocation.setText("<location>");

        jLabel7.setText("Comment");

        txtComment.setEditable(false);
        txtComment.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(73, 73, 73)
                        .addComponent(lblCaseID))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(caseCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(lblAssignedTo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37)
                        .addComponent(lblCaseLocation))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(StatusComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtComment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCaseID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCaseLocation))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAssignedTo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(caseCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnBack)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox StatusComboBox;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox caseCategoryComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssignedTo;
    private javax.swing.JLabel lblCaseID;
    private javax.swing.JLabel lblCaseLocation;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
