/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MonitoringSupervisorRole;

import Business.Enterprise.ComplexEnterprise;
import java.awt.CardLayout;
import java.awt.PopupMenu;
import javax.swing.JPanel;
import userinterface.QualityManagerRole.ManageReportsJPanel;
import userinterface.TechnicianRole.ManageTechReportedCasesJPanel;
import userinterface.WaterSupplyOperatorRole.ManageWaterLevelReports;

/**
 *
 * @author vishakha
 */
public class ComplieReportsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ComplexEnterprise enterprise;

    
    public ComplieReportsJPanel(JPanel userProcessContainer,ComplexEnterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        populateSelectReportCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populateSelectReportCombobox()
    {
        selectReportComboBox.removeAllItems();
        selectReportComboBox.addItem("Water Quality Cases");
        selectReportComboBox.addItem("water Supply Cases");
        selectReportComboBox.addItem("Water Leak Cases");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectReportComboBox = new javax.swing.JComboBox();
        btnProceed = new javax.swing.JButton();
        btnConsolidatedReport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Reporting");

        jLabel2.setText("Select specific Report:");

        selectReportComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnProceed.setText("Proceed");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        btnConsolidatedReport.setText("View consolidated Report");
        btnConsolidatedReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsolidatedReportActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(69, 69, 69)
                        .addComponent(selectReportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProceed))
                    .addComponent(jLabel1)
                    .addComponent(btnConsolidatedReport))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selectReportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProceed))
                .addGap(42, 42, 42)
                .addComponent(btnConsolidatedReport)
                .addGap(85, 85, 85)
                .addComponent(btnBack)
                .addContainerGap(356, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        String type=null;
        if(selectReportComboBox.getSelectedIndex()==0)
        {
            type="WaterQualityWorkRequest";
        }
        if(selectReportComboBox.getSelectedIndex()==1)
        {
            type="WaterPressureWorkRequest";
        }
        if(selectReportComboBox.getSelectedIndex()==2)
        {
            type="WaterPipeLeakWorkRequest";
        }
        ReportingJPanel reportingJPanel=new ReportingJPanel(userProcessContainer,enterprise,type);
//        userProcessContainer.add(reportingJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);   
    }//GEN-LAST:event_btnProceedActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnConsolidatedReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsolidatedReportActionPerformed
    ConsolidatedReportJPanel consolidatedReportJPanel=new ConsolidatedReportJPanel(userProcessContainer,enterprise);
    
    }//GEN-LAST:event_btnConsolidatedReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConsolidatedReport;
    private javax.swing.JButton btnProceed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox selectReportComboBox;
    // End of variables declaration//GEN-END:variables
}
