/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MonitoringSupervisorRole;


import Business.Employee.Employee;
import Business.Employee.Resident;
import Business.Enterprise.ComplexEnterprise;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vishakha
 */
public class ManageResidentsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ComplexEnterprise enterprise;
    public ManageResidentsJPanel(JPanel userProcessContainer,ComplexEnterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        populateResidentsTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populateResidentsTable()
    {
     DefaultTableModel model = (DefaultTableModel)tblResidents.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee : enterprise.getEmployeeDirectory().getEmployeeList()){
            if(employee instanceof Resident)
            {    
            Object[] row = new Object[3];
            row[0] =((Resident)employee).getName();
            row[1] = ((Resident)employee).getFloor();
            row[2]=(Resident)employee;
            model.addRow(row);
            }
        }   
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResidents = new javax.swing.JTable();
        btnCreateNewResident = new javax.swing.JButton();
        btnManageResident = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Residents Details");

        tblResidents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Floor", "Apartment Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblResidents);

        btnCreateNewResident.setText("Create New Resident");
        btnCreateNewResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewResidentActionPerformed(evt);
            }
        });

        btnManageResident.setText("Manage Resident");
        btnManageResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageResidentActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnManageResident)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateNewResident))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateNewResident)
                    .addComponent(btnManageResident))
                .addGap(46, 46, 46)
                .addComponent(btnBack)
                .addContainerGap(219, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNewResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewResidentActionPerformed
        CreateNewResidentsJPanel createNewResidentsJPanel=new CreateNewResidentsJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("createNewResidentsJPanel",createNewResidentsJPanel);
        CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateNewResidentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnManageResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageResidentActionPerformed
        int selectedRow = tblResidents.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Select the row to manage profile");
            return;
        }

        Resident resident=(Resident)tblResidents.getValueAt(selectedRow,0);
        ViewResidentsProfileJPanel viewResidentsProfileJPanel=new ViewResidentsProfileJPanel(userProcessContainer,resident);
        userProcessContainer.add("viewResidentsProfileJPanel",viewResidentsProfileJPanel);
        CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);        
    }//GEN-LAST:event_btnManageResidentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateNewResident;
    private javax.swing.JButton btnManageResident;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResidents;
    // End of variables declaration//GEN-END:variables
}
