/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MonitoringSupervisorRole;

import Business.Enterprise.ComplexEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.MonitoringExecutivesOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vishakha
 */
public class MonitoringSupervisorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    //private MonitoringExecutivesOrganization monitoringExecutivesOrganization;
    private ComplexEnterprise buildingEnterprise;
    private Organization organization;
    public MonitoringSupervisorWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Organization organization,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organization=organization;
        this.userAccount=userAccount;
        //this.monitoringExecutivesOrganization=(MonitoringExecutivesOrganization)organization;
        this.buildingEnterprise=(ComplexEnterprise)enterprise;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCompileReports = new javax.swing.JButton();
        btnMonitoringTasks = new javax.swing.JButton();
        btnResidentsManagement = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Supervisor Work Area");

        btnCompileReports.setText("Compile Reports");
        btnCompileReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompileReportsActionPerformed(evt);
            }
        });

        btnMonitoringTasks.setText("Monitoring Tasks");
        btnMonitoringTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonitoringTasksActionPerformed(evt);
            }
        });

        btnResidentsManagement.setText("Residents Management");
        btnResidentsManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResidentsManagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnResidentsManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(btnMonitoringTasks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCompileReports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(409, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(btnMonitoringTasks)
                .addGap(36, 36, 36)
                .addComponent(btnCompileReports)
                .addGap(33, 33, 33)
                .addComponent(btnResidentsManagement)
                .addContainerGap(308, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResidentsManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResidentsManagementActionPerformed
        ResidentsManagementJPanel residentsManagementJPanel=new ResidentsManagementJPanel(userProcessContainer,buildingEnterprise);
        userProcessContainer.add("residentManagementJPanel",residentsManagementJPanel);
        CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnResidentsManagementActionPerformed

    private void btnMonitoringTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitoringTasksActionPerformed
        MonitoringTasksJPanel monitoringTasksJPanel=new MonitoringTasksJPanel(userProcessContainer,userAccount,organization,buildingEnterprise);
        userProcessContainer.add("monitoringTasksJPanel",monitoringTasksJPanel);
        CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnMonitoringTasksActionPerformed

    private void btnCompileReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompileReportsActionPerformed
        ComplieReportsJPanel complieReportsJPanel=new ComplieReportsJPanel(userProcessContainer,buildingEnterprise);
        userProcessContainer.add("complieReportsJPanel",complieReportsJPanel);
        CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnCompileReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompileReports;
    private javax.swing.JButton btnMonitoringTasks;
    private javax.swing.JButton btnResidentsManagement;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
