/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MonitoringSupervisorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.WorkQueue.WaterPipeLeakWorkRequest;
import Business.WorkQueue.WaterPressureWorkRequest;
import Business.WorkQueue.WaterQualityWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author vishakha
 */
public class ReportingJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private String type;
    private WorkRequest workRequest;
    public ReportingJPanel(JPanel userProcessContainer,Enterprise enterprise,String type) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.type=type;
        populateReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public DefaultTableModel populateReportTable()
    {
        DefaultTableModel model = (DefaultTableModel)tblReport.getModel();
        
        model.setRowCount(0);
        for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(org.getName().contains(Organization.Type.MaintainanceExecutives.getValue()))
            {
                for(WorkRequest request:org.getWorkQueue().getWorkRequestList())
                {
                    if(request instanceof  WaterQualityWorkRequest && request.getClass().getName().contains(type) )
                      {   
                        if(request.getResolveDate()!=null)  
                         {    
                            Object[] row = new Object[5];
                            row[0] = request.toString();
                            //row[1] = request.getMessage();
                            row[1] = ((WaterQualityWorkRequest)request).getCategory();           
                            row[2] = request.getRequestDate().toString();
                            row[3] = request.getResolveDate().toString();
                            row[4] = request.getAssignedTo() == null ? null : request.getAssignedTo().getEmployee().getName();

                            model.addRow(row);
                        }
                       }   
                    
                    if(request instanceof  WaterPressureWorkRequest && request.getClass().getName().contains(type) )
                      {   
                        if(request.getResolveDate()!=null)  
                         {    
                            Object[] row = new Object[5];
                            row[0] = request.toString();
                            //row[1] = request.getMessage();
                            row[1] = ((WaterPressureWorkRequest)request).getCategory();           
                            row[2] = request.getRequestDate().toString();
                            row[3] = request.getResolveDate().toString();
                            row[4] = request.getAssignedTo() == null ? null : request.getAssignedTo().getEmployee().getName();

                            model.addRow(row);
                        }
                       }   
                    
                    if(request instanceof  WaterPipeLeakWorkRequest && request.getClass().getName().contains(type) )
                      {   
                        if(request.getResolveDate()!=null)  
                         {    
                            Object[] row = new Object[5];
                            row[0] = request.toString();
                            //row[1] = request.getMessage();
                            row[1] = ((WaterPipeLeakWorkRequest)request).getCategory();           
                            row[2] = request.getRequestDate().toString();
                            row[3] = request.getResolveDate().toString();
                            row[4] = request.getAssignedTo() == null ? null : request.getAssignedTo().getEmployee().getName();

                            model.addRow(row);
                        }
                       }   
                }
            }
                
        }
        
        return model;
    }
    
    public void populateReport()
    {
        //DefaultTableModel model=populateReportTable();
        JasperPrint jasperPrint = null;
        //TableModelData();
        DefaultTableModel model=populateReportTable();
        if(type.equals("WaterQualityWorkRequest"))
        try {
            JasperCompileManager.compileReportToFile("Reports/report3.jrxml");
            jasperPrint = JasperFillManager.fillReport("Reports/report3.jasper", new HashMap(),
                    new JRTableModelDataSource(model));
            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
            //jasperViewer.setVisible(true);
            jasperViewer.viewReport(jasperPrint,false);
        } catch (JRException ex) {
            ex.printStackTrace();
        }
        
        if(type.equals("WaterPressureWorkRequest"))
            try {
            JasperCompileManager.compileReportToFile("Reports/report2.jrxml");
            jasperPrint = JasperFillManager.fillReport("Reports/report2.jasper", new HashMap(),
                    new JRTableModelDataSource(model));
            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
            //jasperViewer.setVisible(true);
            jasperViewer.viewReport(jasperPrint,false);
        } catch (JRException ex) {
            ex.printStackTrace();
        }
        
        if(type.equals("WaterPipeLeakWorkRequest"))
           try {
            JasperCompileManager.compileReportToFile("Reports/report1.jrxml");
            jasperPrint = JasperFillManager.fillReport("Reports/report1.jasper", new HashMap(),
                    new JRTableModelDataSource(model));
            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
            //jasperViewer.setVisible(true);
            jasperViewer.viewReport(jasperPrint,false);
        } catch (JRException ex) {
            ex.printStackTrace();
        }  
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Case ID", "Case Category", "Request Date", "Resolved Date", "Assigned To"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReport);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Report for the raised Cases");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnBack)
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables
}
