/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MonitoringSupervisorRole;

import Business.Enterprise.ComplexEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vishakha
 */
public class ResidentsManagementJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    //private ResidentsOrganization residentsOrganization;
    private ComplexEnterprise enterprise;
    public ResidentsManagementJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=(ComplexEnterprise)enterprise;

//        for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList())
//            if(org.getClass().getName().contains(Organization.Type.Resident.getValue()))
//                residentsOrganization=(ResidentsOrganization)org;
        //this.residentsOrganization=(ResidentsOrganization)organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageResidentsProfile = new javax.swing.JButton();
        btnAlertResidents = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Residents Management");

        btnManageResidentsProfile.setText("Manage Residents Profile");
        btnManageResidentsProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageResidentsProfileActionPerformed(evt);
            }
        });

        btnAlertResidents.setText("Alert Residents");
        btnAlertResidents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlertResidentsActionPerformed(evt);
            }
        });

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAlertResidents, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageResidentsProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(btnManageResidentsProfile)
                .addGap(40, 40, 40)
                .addComponent(btnAlertResidents)
                .addGap(69, 69, 69)
                .addComponent(jButton1)
                .addContainerGap(261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlertResidentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlertResidentsActionPerformed
    ResidentsRelationsJPanel residentsRelationsJPanel=new ResidentsRelationsJPanel(userProcessContainer,enterprise);
    userProcessContainer.add("residentsRelationJPanel",residentsRelationsJPanel);
    CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
    cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnAlertResidentsActionPerformed

    private void btnManageResidentsProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageResidentsProfileActionPerformed
    ManageResidentsJPanel manageResidentsJPanel=new ManageResidentsJPanel(userProcessContainer,enterprise);
    userProcessContainer.add("manageResidentsJPanel",manageResidentsJPanel);
    CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
    cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageResidentsProfileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlertResidents;
    private javax.swing.JButton btnManageResidentsProfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
