/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdminRole;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;

/**
 *
 * @author vishakha
 */
public class SensorsMapJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private int[] ht=new int[2];
    public SensorsMapJPanel(JPanel userProcessContainer,int[] x) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ht[0]=x[0];
        this.ht[1]=x[1];
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\vishakha\\Desktop\\AED\\Project\\helpMaterial\\1449353158_palm_tree.png")); // NOI18N
        jLabel6.setText("jLabel1");

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(900, 600));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\vishakha\\Desktop\\AED\\Project\\helpMaterial\\1449353158_palm_tree.png")); // NOI18N
        jLabel4.setText("jLabel1");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\vishakha\\Desktop\\AED\\Project\\helpMaterial\\1449353158_palm_tree.png")); // NOI18N
        jLabel5.setText("jLabel1");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\vishakha\\Desktop\\AED\\Project\\helpMaterial\\1449353158_palm_tree.png")); // NOI18N
        jLabel7.setText("jLabel1");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\vishakha\\Desktop\\AED\\Project\\helpMaterial\\1449353158_palm_tree.png")); // NOI18N
        jLabel8.setText("jLabel1");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("1171");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1167");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(184, 184, 184))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void drawRect(int[] x,Graphics g)
            
    {
        g.setColor(Color.red);
        g.fill3DRect(x[1],x[0],25,25, true);
        
    }
    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
//        int x=0;
//        ht=new int
        Graphics2D g= (Graphics2D)getGraphics();
        g.fill3DRect(10, 70, 290,500,true);
        
        Graphics2D pipe1=(Graphics2D)getGraphics();
        pipe1.setColor(Color.RED);
        pipe1.fill3DRect(280,70,10,490, true);
        
        Graphics2D sensor1=(Graphics2D)getGraphics();
        sensor1.setColor(Color.CYAN);
        
        Graphics2D g1=(Graphics2D) getGraphics();//building 1
        g1.setColor(Color.WHITE);
        
        //sensor1.fill3DRect(200, 40,30,30, true);//quantity sensor1
        sensor1.fill3DRect(250,50,25,25, true);
        
        g1.fill3DRect(30,70,50,40,false);
        g1.fill3DRect(90,70,50,40,false);
        g1.fill3DRect(30,120,50,40,false);
        g1.fill3DRect(90,120,50,40,false);
        g1.fill3DRect(160,70,120,90,true);//big window 1
        
        sensor1.fill3DRect(270,100,25,25, true);
        sensor1.drawString("5F#51", 300,100);
        
        g1.fill3DRect(30,170,50,40,false);
        g1.fill3DRect(90,170,50,40,false);
        g1.fill3DRect(30,220,50,40,false);
        g1.fill3DRect(90,220,50,40,false);
        g1.fill3DRect(160,170,120,90,true);//big window 2
        
        sensor1.fill3DRect(270,200,25,25, true);
        sensor1.drawString("4F#41", 300,200);
        
        g1.fill3DRect(30,270,50,40,false);
        g1.fill3DRect(90,270,50,40,false);
        g1.fill3DRect(30,320,50,40,false);
        g1.fill3DRect(90,320,50,40,false);
        g1.fill3DRect(160,270,120,90,true);//big window 3
        
        sensor1.fill3DRect(270,300,25,25, true);
        sensor1.drawString("3F#31", 300,300);
        
        g1.fill3DRect(30,370,50,40,false);
        g1.fill3DRect(90,370,50,40,false);
        g1.fill3DRect(30,420,50,40,false);
        g1.fill3DRect(90,420,50,40,false);
        g1.fill3DRect(160,370,120,90,true);//big window 4
        
        sensor1.fill3DRect(270,400,25,25, true);
        sensor1.drawString("2F#21", 300,400);
        
        g1.fill3DRect(30,470,50,40,false);
        g1.fill3DRect(90,470,50,40,false);
        g1.fill3DRect(30,520,50,40,false);
        g1.fill3DRect(90,520,50,40,false);
        g1.fill3DRect(160,470,120,90,true);//big window 5 
        
        sensor1.fill3DRect(270,500,25,25, true);
        sensor1.drawString("1F#11", 300,500);
        
        sensor1.fill3DRect(250,550,25,25, true);
        
        Graphics2D pipe2=(Graphics2D)getGraphics();
        pipe2.setColor(Color.RED);
        pipe2.fill3DRect(650,70,10,490, true);
        
//        Graphics2D sensor2=(Graphics2D)getGraphics();
//        sensor2.setColor(Color.CYAN);
        //sensor1.fill3DRect(570, 40,30,30, true);//quantity sensor2
        sensor1.fill3DRect(620,50,25,25, true);
        
        Graphics2D g2=(Graphics2D) getGraphics();//building 2
        g2.setColor(Color.yellow);
        g2.fill3DRect(400,70,50,40,false);
        g2.fill3DRect(460,70,50,40,false);
        g2.fill3DRect(400,120,50,40,false);
        g2.fill3DRect(460,120,50,40,false);
        g2.fill3DRect(530,70,120,90,true);//big window 1
        
        sensor1.fill3DRect(640,100,25,25, true);
        sensor1.drawString("5F#51", 670,100);
        
        g2.fill3DRect(400,170,50,40,false);
        g2.fill3DRect(460,170,50,40,false);
        g2.fill3DRect(400,220,50,40,false);
        g2.fill3DRect(460,220,50,40,false);
        g2.fill3DRect(530,170,120,90,true);//big window 2
        
        sensor1.fill3DRect(640,200,25,25, true);
        sensor1.drawString("4F#41", 670,200);
        
        g2.fill3DRect(400,270,50,40,false);
        g2.fill3DRect(460,270,50,40,false);
        g2.fill3DRect(400,320,50,40,false);
        g2.fill3DRect(460,320,50,40,false);
        g2.fill3DRect(530,270,120,90,true);//big window 3
        
        sensor1.fill3DRect(640,300,25,25, true);
        sensor1.drawString("3F#31", 670,300);
        
        g2.fill3DRect(400,370,50,40,false);
        g2.fill3DRect(460,370,50,40,false);
        g2.fill3DRect(400,420,50,40,false);
        g2.fill3DRect(460,420,50,40,false);
        g2.fill3DRect(530,370,120,90,true);//big window 4
        
        sensor1.fill3DRect(640,400,25,25, true);
        sensor1.drawString("2F#21", 670,400);
        
        g2.fill3DRect(400,470,50,40,false);
        g2.fill3DRect(460,470,50,40,false);
        g2.fill3DRect(400,520,50,40,false);
        g2.fill3DRect(460,520,50,40,false);
        g2.fill3DRect(530,470,120,90,true);//big window 5 
        
        sensor1.fill3DRect(640,500,25,25, true);
        sensor1.drawString("1F#11", 670,500);
        
        sensor1.fill3DRect(620,550,25,25, true);
        
        if(ht[0]!=0)
        drawRect(ht,sensor1);
        
    }//GEN-LAST:event_formAncestorAdded

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
         
    }//GEN-LAST:event_formFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
