/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.TechnicianRole;

import Business.EcoSystem;
import Business.Organization.MaintainanceExecutiveOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vishakha
 */
public class TechnicianWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private MaintainanceExecutiveOrganization maintainanceExecutiveOrganization;
    private EcoSystem business;
    
    public TechnicianWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Organization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.maintainanceExecutiveOrganization=(MaintainanceExecutiveOrganization)organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageReportedCases = new javax.swing.JButton();
        btnManageReports = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Technician Work Area");

        btnManageReportedCases.setText("Manage Reported Cases");
        btnManageReportedCases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageReportedCasesActionPerformed(evt);
            }
        });

        btnManageReports.setText("Manage Reports");
        btnManageReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnManageReports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageReportedCases, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(btnManageReportedCases)
                .addGap(44, 44, 44)
                .addComponent(btnManageReports)
                .addContainerGap(391, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageReportedCasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageReportedCasesActionPerformed
        ManageTechReportedCasesJPanel manageReportedCasesJPanel = new ManageTechReportedCasesJPanel(userProcessContainer,maintainanceExecutiveOrganization,userAccount);
        userProcessContainer.add("manageReportedCasesJPanel", manageReportedCasesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageReportedCasesActionPerformed

    private void btnManageReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageReportsActionPerformed
        ManageTechReportsJPanel manageTechReportsJPanel= new ManageTechReportsJPanel(userProcessContainer,userAccount,maintainanceExecutiveOrganization);
//////        userProcessContainer.add("manageTechReportsJPanel", manageTechReportsJPanel);
//////        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//////        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageReportedCases;
    private javax.swing.JButton btnManageReports;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
