/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.WaterSupplyOperatorRole;

import Business.WorkQueue.WaterPressureWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.AdminRole.SensorsMapJPanel;

/**
 *
 * @author vishakha
 */
public class ProcessSupplyWorkRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private WaterPressureWorkRequest request;
    int [] x=new int[2];
    public ProcessSupplyWorkRequestJPanel(JPanel userProcessContainer,WaterPressureWorkRequest request) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        populateCaseCategory();
        populateCaseStatus();
        populateData();
    }

    public void populateCaseCategory()
    {
        caseCategoryComboBox.removeAllItems();
        for(String caseCategory:request.getCaseCategory())
            caseCategoryComboBox.addItem(caseCategory);
        if(request.getCategory()!=null)
            caseCategoryComboBox.setSelectedItem(request.getCategory());
    
    }
    
    public void populateCaseStatus()
    {
        StatusComboBox.removeAllItems();
        for(String status:request.getStatusList())
            StatusComboBox.addItem(status);
        if(request.getStatus()!=null)
        {
            StatusComboBox.setSelectedItem(request.getStatus());
            txtDescription.setText(request.getDescription());
            txtComment.setText(request.getComment());
        }
    
    }
    public void populateData()
    {
        lblCaseID.setText(String.valueOf(request));
        lblAssignedTo.setText(request.getAssignedTo().getEmployee().getName());
        lblCaseLocation.setText(request.getLocation());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCaseID = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblAssignedTo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        caseCategoryComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        lblCaseLocation = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtComment = new javax.swing.JTextField();
        btnCheckLocation = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();

        lblCaseID.setText("<caseID>");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setText("AssignedTo:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblAssignedTo.setText("<assignedTo>");

        jLabel3.setText("Case Category:");

        caseCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        jLabel5.setText("Status:");

        jLabel1.setText("CaseID:");

        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Case Location:");

        lblCaseLocation.setText("<caseLocation>");

        jLabel7.setText("Comment");

        btnCheckLocation.setText("Check Location");
        btnCheckLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckLocationActionPerformed(evt);
            }
        });

        jLabel8.setText("Message");

        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(179, 179, 179)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCaseLocation)
                                .addGap(65, 65, 65)
                                .addComponent(btnCheckLocation))
                            .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caseCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAssignedTo)
                            .addComponent(lblCaseID)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMessage, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtComment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCaseID))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAssignedTo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCaseLocation)
                    .addComponent(btnCheckLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(caseCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSubmit))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageWaterSupplyIssuesJPanel dwjp = (ManageWaterSupplyIssuesJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        if(!txtDescription.getText().trim().isEmpty() && !txtComment.getText().trim().isEmpty())
        {
        request.setStatus(StatusComboBox.getSelectedItem().toString());
        request.setDescription(txtDescription.getText());
        request.setCategory(caseCategoryComboBox.getSelectedItem().toString());
        request.setComment(txtComment.getText());  
        if(request.getStatus().equals("Completed"))
        request.setResolveDate(new Date());
        request.setMessage(txtMessage.getText());
        JOptionPane.showMessageDialog(null,"Request processed successfully");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Fields cannot be Empty!");
            txtDescription.setText("");
            txtComment.setText("");
            txtDescription.grabFocus();
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    public int[] checkLocation()
    {
      String location=request.getLocation();
      String building=request.getBuilding().getBuildingName();
      if(building.contains("1171"))
      {
          if(location.contains("Top"))
           x[0]=50;
          else
              x[0]=550;
          x[1]=250;
      }
            if(building.contains("1167"))
      {
           if(location.contains("Top"))
           x[0]=50;
          else
              x[0]=550;
          x[1]=620;
      }
       return x;     
    }
    
    private void btnCheckLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckLocationActionPerformed
        int y[]=checkLocation();
        SensorsMapJPanel sensorsMapJPanel=new SensorsMapJPanel(userProcessContainer,y);
        userProcessContainer.add("sensorsMapJPanel",sensorsMapJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);  
    }//GEN-LAST:event_btnCheckLocationActionPerformed

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox StatusComboBox;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckLocation;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox caseCategoryComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssignedTo;
    private javax.swing.JLabel lblCaseID;
    private javax.swing.JLabel lblCaseLocation;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
